#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow "Nginx HTTP"
sed -i "/^http {/a \    add_header X-Served-By $HOST_NAME;" /etc/nginx/sites-available/default
echo "Hello World!" | tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/index.html

sudo nginx -t
sudo service nginx restart
