#!/usr/bin/env bash
# What is the OSI model? and How is the OSI model organized?
# 2: The OSI model is a conceptual model that characterises the communication
# functions of a telecommunication system without regards
# to their underlying internal structure and technology

2
2
