#!/usr/bin/env bash
# A bash script that displays a list of all current processes
# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format and show process hierarchy

ps auxf
