#!/usr/bin/env bash
# This scripts is displaying "Best School" 10 times with an hi after the 9t

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 8 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done
